import type { ActionScenario } from './action_sequence_runner';

export const ACTION_SEQUENCE_SCENARIOS: ActionScenario[] = [
  {
    name: 'rename_via_list_and_canvas_then_match_width',
    actions: [
      { kind: 'reset' },
      { kind: 'assertCounts', elements: 0, constraints: 0, constants: 0 },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Width' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match width.' },
      { kind: 'selectElementList', target: { by: 'text', value: 'left_panel' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MC4xLCJ5IjowLjEsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJyaWdodF9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX1dLCJjb25zdGFudHMiOltdLCJ2aWV3cG9ydCI6eyJ3aWR0aCI6Nzk4LCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMjAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjV9fQ==',
  },
  {
    name: 'canvas_click_completes_align_left',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Align Left' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to align left with.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MCwieSI6MC4xLCJ3aWR0aCI6MSwiaGVpZ2h0IjoxLCJ0ZXh0IjoicmlnaHRfcGFuZWwifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'canvas_click_completes_align_bottom',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'top_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'bottom_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'bottom_panel' } },
      { kind: 'clickPresetConstraint', name: 'Align Bottom' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to align bottom with.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJ0b3BfcGFuZWwifSx7ImlkIjoiYXhpcy0xIiwidHlwZSI6ImF4aXMiLCJ4IjowLjEsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJib3R0b21fcGFuZWwifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieSJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'canvas_click_completes_match_width',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Width' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match width.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MC4xLCJ5IjowLjEsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJyaWdodF9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX1dLCJjb25zdGFudHMiOltdLCJ2aWV3cG9ydCI6eyJ3aWR0aCI6Nzk4LCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMjAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjV9fQ==',
  },
  {
    name: 'canvas_click_completes_match_height',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'top_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'bottom_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'bottom_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Height' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match height.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJ0b3BfcGFuZWwifSx7ImlkIjoiYXhpcy0xIiwidHlwZSI6ImF4aXMiLCJ4IjowLjEsInkiOjAuMSwid2lkdGgiOjEsImhlaWdodCI6MSwidGV4dCI6ImJvdHRvbV9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJoZWlnaHQifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6ImhlaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'custom_constraint_with_source_attr',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'first' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'second' },
      {
        kind: 'addConstraint',
        targetAttr: 'x',
        source: { by: 'alias', value: 'axis1' },
        sourceAttr: 'right',
      },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJmaXJzdCJ9LHsiaWQiOiJheGlzLTEiLCJ0eXBlIjoiYXhpcyIsIngiOjEsInkiOjAuMSwid2lkdGgiOjEsImhlaWdodCI6MSwidGV4dCI6InNlY29uZCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJyaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'axes_with_spacing_and_shared_width_constant',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis_left' },
      { kind: 'addAxis', alias: 'axis_right' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis_left' } },
      { kind: 'renameSelected', prop: 'text', value: 'axis_left' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis_right' } },
      { kind: 'renameSelected', prop: 'text', value: 'axis_right' },
      { kind: 'addConstant', alias: 'const_width' },
      { kind: 'selectConstantList', target: { by: 'alias', value: 'const_width' } },
      { kind: 'renameSelected', prop: 'value', value: '1' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis_right' } },
      {
        kind: 'addConstraint',
        targetAttr: 'x',
        source: { by: 'alias', value: 'axis_left' },
        sourceAttr: 'right',
        addAfter: 0.2,
      },
      {
        kind: 'addConstraint',
        targetAttr: 'width',
        source: { by: 'constant', value: 'const_width' },
      },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis_left' } },
      {
        kind: 'addConstraint',
        targetAttr: 'width',
        source: { by: 'alias', value: 'axis_right' },
        sourceAttr: 'width',
      },
      { kind: 'assertCounts', elements: 2, constraints: 3, constants: 1 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJheGlzX2xlZnQifSx7ImlkIjoiYXhpcy0xIiwidHlwZSI6ImF4aXMiLCJ4IjoxLjIsInkiOjAuMSwid2lkdGgiOjEsImhlaWdodCI6MSwidGV4dCI6ImF4aXNfcmlnaHQifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoicmlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowLjJ9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJjb25zdGFudDAiLCJhdHRyIjpudWxsfSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwic291cmNlIjp7ImlkIjoiYXhpcy0xIiwiYXR0ciI6IndpZHRoIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19XSwiY29uc3RhbnRzIjpbeyJpZCI6ImNvbnN0YW50MCIsInZhbHVlIjoxfV0sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'custom_complex_layout_only_base64_check',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_bottom' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_top' },
      { kind: 'addAxis', alias: 'axis3' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis3' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_cbar' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'clickPresetConstraint', name: 'Match Height' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'clickPresetConstraint', name: 'Match Width' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'clickPresetConstraint', name: 'Align Left' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis3' } },
      { kind: 'clickPresetConstraint', name: 'Align Bottom' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'addConstant', alias: 'cbar_width' },
      { kind: 'selectConstantList', target: { by: 'alias', value: 'cbar_width' } },
      { kind: 'renameSelected', prop: 'id', value: 'cbar_width' },
      { kind: 'renameSelected', prop: 'value', value: '0.2' },
      { kind: 'addConstant', alias: 'cbar_spacing' },
      { kind: 'selectConstantList', target: { by: 'alias', value: 'cbar_spacing' } },
      { kind: 'renameSelected', prop: 'id', value: 'cbar_spacing' },
      { kind: 'renameSelected', prop: 'value', value: '0.1' },
      { kind: 'addConstant', alias: 'vert_spacing' },
      { kind: 'selectConstantList', target: { by: 'alias', value: 'vert_spacing' } },
      { kind: 'renameSelected', prop: 'id', value: 'vert_spacing' },
      { kind: 'renameSelected', prop: 'value', value: '0.15' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis3' } },
      {
        kind: 'addConstraint',
        targetAttr: 'x',
        source: { by: 'alias', value: 'axis1' },
        sourceAttr: 'right',
        addAfter: { by: 'constant', value: 'cbar_spacing' },
      },
      {
        kind: 'addConstraint',
        targetAttr: 'width',
        source: { by: 'constant', value: 'cbar_width' },
      },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      {
        kind: 'addConstraint',
        targetAttr: 'y',
        source: { by: 'alias', value: 'axis1' },
        sourceAttr: 'top',
        addAfter: { by: 'constant', value: 'vert_spacing' },
      },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X2JvdHRvbSJ9LHsiaWQiOiJheGlzLTEiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjEuMTUsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3RvcCJ9LHsiaWQiOiJheGlzLTIiLCJ0eXBlIjoiYXhpcyIsIngiOjEuMSwieSI6MCwid2lkdGgiOjAuMiwiaGVpZ2h0IjoxLCJ0ZXh0IjoibGVmdF9jYmFyIn1dLCJjb25zdHJhaW50cyI6W3sidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xIiwiYXR0ciI6ImhlaWdodCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoiaGVpZ2h0In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xIiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0yIiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTIiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoicmlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjoiY2Jhcl9zcGFjaW5nIiwiYXR0ciI6bnVsbH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0yIiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImNiYXJfd2lkdGgiLCJhdHRyIjpudWxsfSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoidG9wIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6InZlcnRfc3BhY2luZyIsImF0dHIiOm51bGx9fV0sImNvbnN0YW50cyI6W3siaWQiOiJjYmFyX3dpZHRoIiwidmFsdWUiOjAuMn0seyJpZCI6ImNiYXJfc3BhY2luZyIsInZhbHVlIjowLjF9LHsiaWQiOiJ2ZXJ0X3NwYWNpbmciLCJ2YWx1ZSI6MC4xNX1dLCJ2aWV3cG9ydCI6eyJ3aWR0aCI6Nzk4LCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMjAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjV9fQ==',
  }
];
