import type { ActionScenario } from './action_sequence_runner';

export const ACTION_SEQUENCE_SCENARIOS: ActionScenario[] = [
  {
    name: 'rename_via_list_and_canvas_then_match_width',
    actions: [
      { kind: 'reset' },
      { kind: 'assertCounts', elements: 0, constraints: 0, constants: 0 },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Width' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match width.' },
      { kind: 'selectElementList', target: { by: 'text', value: 'left_panel' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MC4xLCJ5IjowLjEsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJyaWdodF9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX1dLCJjb25zdGFudHMiOltdLCJ2aWV3cG9ydCI6eyJ3aWR0aCI6Nzk4LCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMjAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjV9fQ==',
  },
  {
    name: 'canvas_click_completes_align_left',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Align Left' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to align left with.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MCwieSI6MC4xLCJ3aWR0aCI6MSwiaGVpZ2h0IjoxLCJ0ZXh0IjoicmlnaHRfcGFuZWwifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'canvas_click_completes_align_bottom',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'top_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'bottom_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'bottom_panel' } },
      { kind: 'clickPresetConstraint', name: 'Align Bottom' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to align bottom with.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJ0b3BfcGFuZWwifSx7ImlkIjoiYXhpcy0xIiwidHlwZSI6ImF4aXMiLCJ4IjowLjEsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJib3R0b21fcGFuZWwifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieSJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'canvas_click_completes_match_width',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'left_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'right_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'right_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Width' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match width.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJsZWZ0X3BhbmVsIn0seyJpZCI6ImF4aXMtMSIsInR5cGUiOiJheGlzIiwieCI6MC4xLCJ5IjowLjEsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJyaWdodF9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX1dLCJjb25zdGFudHMiOltdLCJ2aWV3cG9ydCI6eyJ3aWR0aCI6Nzk4LCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMjAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjV9fQ==',
  },
  {
    name: 'canvas_click_completes_match_height',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'top_panel' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'bottom_panel' },
      { kind: 'selectElementList', target: { by: 'text', value: 'bottom_panel' } },
      { kind: 'clickPresetConstraint', name: 'Match Height' },
      { kind: 'assertStatusText', text: 'Waiting for input: select element to match height.' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJ0b3BfcGFuZWwifSx7ImlkIjoiYXhpcy0xIiwidHlwZSI6ImF4aXMiLCJ4IjowLjEsInkiOjAuMSwid2lkdGgiOjEsImhlaWdodCI6MSwidGV4dCI6ImJvdHRvbV9wYW5lbCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJoZWlnaHQifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6ImhlaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
  {
    name: 'custom_constraint_with_source_attr',
    actions: [
      { kind: 'reset' },
      { kind: 'addAxis', alias: 'axis1' },
      { kind: 'addAxis', alias: 'axis2' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis1' } },
      { kind: 'renameSelected', prop: 'text', value: 'first' },
      { kind: 'selectElementList', target: { by: 'alias', value: 'axis2' } },
      { kind: 'renameSelected', prop: 'text', value: 'second' },
      {
        kind: 'addConstraint',
        targetAttr: 'x',
        source: { by: 'alias', value: 'axis1' },
        sourceAttr: 'right',
      },
      { kind: 'assertCounts', elements: 2, constraints: 1, constants: 0 },
    ],
    expectedExport: 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAsInkiOjAsIndpZHRoIjoxLCJoZWlnaHQiOjEsInRleHQiOiJmaXJzdCJ9LHsiaWQiOiJheGlzLTEiLCJ0eXBlIjoiYXhpcyIsIngiOjEsInkiOjAuMSwid2lkdGgiOjEsImhlaWdodCI6MSwidGV4dCI6InNlY29uZCJ9XSwiY29uc3RyYWludHMiOlt7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJyaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fV0sImNvbnN0YW50cyI6W10sInZpZXdwb3J0Ijp7IndpZHRoIjo3OTgsImhlaWdodCI6MTAwMCwic2NhbGUiOjEyMCwiZmlndXJlV2lkdGgiOjcsImZpZ3VyZUhlaWdodCI6NX19',
  },
];
