import { expect, test } from '@playwright/test';

type LayoutElement = {
  id: string;
  type: string;
  text?: string;
};

type LayoutConstraint = {
  target: { id: string; attr: string };
};

type LayoutConstant = {
  id: string;
  value: number;
};

type LayoutViewport = {
  width: number;
  height: number;
  scale: number;
  figureWidth: number;
  figureHeight: number;
};

type LayoutPayload = {
  elements: LayoutElement[];
  constraints: LayoutConstraint[];
  constants: LayoutConstant[];
  viewport: LayoutViewport;
};

const SERIALIZED_LAYOUT = 'eyJlbGVtZW50cyI6W3siaWQiOiJheGlzLTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAuNDcsInkiOjUuNiwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJ0b3BfMSJ9LHsiaWQiOiJheGlzLTEiLCJ0eXBlIjoiYXhpcyIsIngiOjEuODEsInkiOjUuNiwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJ0b3BfMiJ9LHsiaWQiOiJheGlzLTIiLCJ0eXBlIjoiYXhpcyIsIngiOjMuMTUsInkiOjUuNiwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJ0b3BfMyJ9LHsiaWQiOiJheGlzLTMiLCJ0eXBlIjoiYXhpcyIsIngiOjQuNDksInkiOjUuNiwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJ0b3BfNCJ9LHsiaWQiOiJheGlzLTQiLCJ0eXBlIjoiYXhpcyIsIngiOjUuODMsInkiOjUuNiwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJ0b3BfNSJ9LHsiaWQiOiJheGlzLTUiLCJ0eXBlIjoiYXhpcyIsIngiOjAuNDcsInkiOjAuNDYsIndpZHRoIjoxLjEsImhlaWdodCI6Mi4yLCJ0ZXh0IjoiYm90dG9tXzEifSx7ImlkIjoiYXhpcy02IiwidHlwZSI6ImF4aXMiLCJ4IjoxLjgxLCJ5IjowLjQ2LCJ3aWR0aCI6MS4xLCJoZWlnaHQiOjIuMiwidGV4dCI6ImJvdHRvbV8yIn0seyJpZCI6ImF4aXMtNyIsInR5cGUiOiJheGlzIiwieCI6My4xNSwieSI6MC40Niwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJib3R0b21fMyJ9LHsiaWQiOiJheGlzLTgiLCJ0eXBlIjoiYXhpcyIsIngiOjQuNDksInkiOjAuNDYsIndpZHRoIjoxLjEsImhlaWdodCI6Mi4yLCJ0ZXh0IjoiYm90dG9tXzQifSx7ImlkIjoiYXhpcy05IiwidHlwZSI6ImF4aXMiLCJ4Ijo1LjgzLCJ5IjowLjQ2LCJ3aWR0aCI6MS4xLCJoZWlnaHQiOjIuMiwidGV4dCI6ImJvdHRvbV81In0seyJpZCI6ImF4aXMtMTAiLCJ0eXBlIjoiYXhpcyIsIngiOjAuNDcsInkiOjIuOSwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJtaWRkbGVfMSJ9LHsiaWQiOiJheGlzLTExIiwidHlwZSI6ImF4aXMiLCJ4IjoxLjgxLCJ5IjoyLjksIndpZHRoIjoxLjEsImhlaWdodCI6Mi4yLCJ0ZXh0IjoibWlkZGxlXzIifSx7ImlkIjoiYXhpcy0xMiIsInR5cGUiOiJheGlzIiwieCI6My4xNSwieSI6Mi45LCJ3aWR0aCI6MS4xLCJoZWlnaHQiOjIuMiwidGV4dCI6Im1pZGRsZV8zIn0seyJpZCI6ImF4aXMtMTMiLCJ0eXBlIjoiYXhpcyIsIngiOjQuNDksInkiOjIuOSwid2lkdGgiOjEuMSwiaGVpZ2h0IjoyLjIsInRleHQiOiJtaWRkbGVfNCJ9LHsiaWQiOiJheGlzLTE0IiwidHlwZSI6ImF4aXMiLCJ4Ijo1LjgzLCJ5IjoyLjksIndpZHRoIjoxLjEsImhlaWdodCI6Mi4yLCJ0ZXh0IjoibWlkZGxlXzUifV0sImNvbnN0cmFpbnRzIjpbeyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoicmlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjoiaF9zcGFjaW5nIiwiYXR0ciI6bnVsbH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0yIiwiYXR0ciI6IngifSwic291cmNlIjp7ImlkIjoiYXhpcy0xIiwiYXR0ciI6InJpZ2h0In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6Imhfc3BhY2luZyIsImF0dHIiOm51bGx9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMyIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMiIsImF0dHIiOiJyaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOiJoX3NwYWNpbmciLCJhdHRyIjpudWxsfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTQiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTMiLCJhdHRyIjoicmlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjoiaF9zcGFjaW5nIiwiYXR0ciI6bnVsbH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xIiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTIiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieSJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMyIsImF0dHIiOiJ5In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ5In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy00IiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTUiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNiIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy05IiwiYXR0ciI6IngifSwic291cmNlIjp7ImlkIjoiYXhpcy00IiwiYXR0ciI6IngifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTgiLCJhdHRyIjoieCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTMiLCJhdHRyIjoieCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNyIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMiIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy05IiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy01IiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTgiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTUiLCJhdHRyIjoieSJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNyIsImF0dHIiOiJ5In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtNSIsImF0dHIiOiJ5In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy02IiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy01IiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6Mn0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTIiLCJhdHRyIjoid2lkdGgifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6IndpZHRoIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0zIiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNCIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTIiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTMiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTQiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTkiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTUiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTYiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTciLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTgiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTE0IiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy0xMyIsImF0dHIiOiJ5In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMyIsImF0dHIiOiJ5In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMTAiLCJhdHRyIjoieSJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTIiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTEwIiwiYXR0ciI6InkifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTExIiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy0xMCIsImF0dHIiOiJ5In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMCIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMSIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMSIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMiIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMiIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMyIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMyIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xNCIsImF0dHIiOiJ4In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtNCIsImF0dHIiOiJ4In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMCIsImF0dHIiOiJoZWlnaHQifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6ImhlaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTEiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEyIiwiYXR0ciI6ImhlaWdodCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoiaGVpZ2h0In0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy0xMyIsImF0dHIiOiJoZWlnaHQifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6ImhlaWdodCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTQiLCJhdHRyIjoiaGVpZ2h0In0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJoZWlnaHQifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEwIiwiYXR0ciI6InkifSwic291cmNlIjp7ImlkIjoiYXhpcy01IiwiYXR0ciI6InRvcCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOiJoX3NwYWNpbmciLCJhdHRyIjpudWxsfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEwIiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNyIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTEyIiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTMiLCJhdHRyIjoid2lkdGgifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6IndpZHRoIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy05IiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTQiLCJhdHRyIjoid2lkdGgifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6IndpZHRoIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy04IiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtMTEiLCJhdHRyIjoid2lkdGgifSwic291cmNlIjp7ImlkIjoiYXhpcy0wIiwiYXR0ciI6IndpZHRoIn0sIm11bHRpcGx5Ijp7ImlkIjpudWxsLCJhdHRyIjoxfSwiYWRkX2JlZm9yZSI6eyJpZCI6bnVsbCwiYXR0ciI6MH0sImFkZF9hZnRlciI6eyJpZCI6bnVsbCwiYXR0ciI6MH19LHsidGFyZ2V0Ijp7ImlkIjoiYXhpcy02IiwiYXR0ciI6IndpZHRoIn0sInNvdXJjZSI6eyJpZCI6ImF4aXMtMCIsImF0dHIiOiJ3aWR0aCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOm51bGwsImF0dHIiOjB9fSx7InRhcmdldCI6eyJpZCI6ImF4aXMtNSIsImF0dHIiOiJ3aWR0aCJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoid2lkdGgifSwibXVsdGlwbHkiOnsiaWQiOm51bGwsImF0dHIiOjF9LCJhZGRfYmVmb3JlIjp7ImlkIjpudWxsLCJhdHRyIjowfSwiYWRkX2FmdGVyIjp7ImlkIjpudWxsLCJhdHRyIjowfX0seyJ0YXJnZXQiOnsiaWQiOiJheGlzLTAiLCJhdHRyIjoieSJ9LCJzb3VyY2UiOnsiaWQiOiJheGlzLTEwIiwiYXR0ciI6InRvcCJ9LCJtdWx0aXBseSI6eyJpZCI6bnVsbCwiYXR0ciI6MX0sImFkZF9iZWZvcmUiOnsiaWQiOm51bGwsImF0dHIiOjB9LCJhZGRfYWZ0ZXIiOnsiaWQiOiJ2X3NwYWNpbmciLCJhdHRyIjpudWxsfX1dLCJjb25zdGFudHMiOlt7ImlkIjoidl9zcGFjaW5nIiwidmFsdWUiOjAuNX0seyJpZCI6Imhfc3BhY2luZyIsInZhbHVlIjowLjI0fV0sInZpZXdwb3J0Ijp7IndpZHRoIjoyNDYyLCJoZWlnaHQiOjEwMDAsInNjYWxlIjoxMDAsImZpZ3VyZVdpZHRoIjo3LCJmaWd1cmVIZWlnaHQiOjh9fQ==';

function decodeLayout(serialized: string): LayoutPayload {
  const decoded = Buffer.from(serialized, 'base64').toString('utf8');
  return JSON.parse(decoded) as LayoutPayload;
}

test('reset then import serialized layout string and verify imported state', async ({ page }) => {
  const expectedLayout = decodeLayout(SERIALIZED_LAYOUT);

  await page.goto('/ui');

  await page.evaluate(() => {
    localStorage.clear();
    localStorage.setItem('autosave-enabled', 'true');
  });
  await page.reload();

  await page.getByRole('button', { name: 'Reset' }).click();

  await expect(page.locator('.draggable')).toHaveCount(0);
  await expect(page.locator('#constants-list .list-item')).toHaveCount(0);
  await expect(page.locator('#constraints-list .list-item')).toHaveCount(0);

  await page.getByRole('button', { name: 'Import/Export' }).click();
  const importExportModal = page.locator('.import-export-modal');
  await expect(importExportModal).toBeVisible();

  await importExportModal.locator('.import-export-textarea').fill(SERIALIZED_LAYOUT);
  await importExportModal.getByRole('button', { name: 'Import' }).click();

  await expect(importExportModal).toHaveCount(0);

  await expect(page.locator('.draggable')).toHaveCount(expectedLayout.elements.length);
  await expect(page.locator('#elements-list .list-item')).toHaveCount(expectedLayout.elements.length);
  await expect(page.locator('#constants-list .list-item')).toHaveCount(expectedLayout.constants.length);
  await expect(page.locator('#constraints-list .list-item')).toHaveCount(expectedLayout.constraints.length);

  const elementsListText = await page.locator('#elements-list').innerText();
  for (const element of expectedLayout.elements) {
    const name = element.text ?? element.type;
    await expect(page.locator('.draggable', { hasText: name })).toHaveCount(1);
    expect(elementsListText).toContain(name);
  }

  const constantsListText = await page.locator('#constants-list').innerText();
  for (const constant of expectedLayout.constants) {
    expect(constantsListText).toContain(constant.id);
  }

  await page.getByRole('button', { name: 'Import/Export' }).click();
  const exportedSerializedLayout = await page
    .locator('.import-export-modal .import-export-textarea')
    .inputValue();
  const exportedLayout = decodeLayout(exportedSerializedLayout);

  expect(exportedLayout.constraints).toHaveLength(expectedLayout.constraints.length);
  expect(exportedLayout.constants).toHaveLength(expectedLayout.constants.length);

  const exportedElementIds = new Set(exportedLayout.elements.map((element) => element.id));
  for (const element of expectedLayout.elements) {
    expect(exportedElementIds.has(element.id)).toBeTruthy();
  }

  const exportedConstantIds = new Set(exportedLayout.constants.map((constant) => constant.id));
  for (const constant of expectedLayout.constants) {
    expect(exportedConstantIds.has(constant.id)).toBeTruthy();
  }

  expect(exportedLayout.viewport.scale).toBe(expectedLayout.viewport.scale);
  expect(exportedLayout.viewport.figureWidth).toBe(expectedLayout.viewport.figureWidth);
  expect(exportedLayout.viewport.figureHeight).toBe(expectedLayout.viewport.figureHeight);
});
